# This is a basic workflow to help you get started with Actions

name: Html5 Build 

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: build web
        run: |
          RefreshEnv
          haxelib setup C:\haxelib
          haxelib install lime 
          RefreshEnv
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install flixel-addons
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git polymod https://github.com/MasterEric/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git https://github.com/gingerphoenix10/extension-webm.git 
          haxelib run lime rebuild extension-webm windows 
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
          haxelib install actuate 
          haxelib list
          haxelib run lime build html5
        shell: cmd
      - name: compiling and sending off
      - run: haxelib run lime build windows --app-version="DEV-${{ github.run_id}}"
      - name: uploading build            
      - uses: actions/upload-artifact@v2
        with:
          name: Html5 Build
          path: export/release/windows/bin